//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace nXML {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class TestCaseDescription {
        
        private Documentation_cls documentationField;
        
        private ExternalVars_cls[] externalVarsField;
        
        private Instrument_cls[] instrumentsSetupField;
        
        private HardwareSetupType hardwareSetupField;
        
        private ChipSetupType chipSetupField;
        
        private TestProcedure_cls testProcedureField;
        
        private ProcessResults_cls storeResultsField;
        
        private SchemaInfoType schemaInfoField;
        
        private SupportEnums_cls supportEnumsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Documentation_cls Documentation {
            get {
                return this.documentationField;
            }
            set {
                this.documentationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExternalVars", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ExternalVars_cls[] ExternalVars {
            get {
                return this.externalVarsField;
            }
            set {
                this.externalVarsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InstrumentsSetup", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Instrument_cls[] InstrumentsSetup {
            get {
                return this.instrumentsSetupField;
            }
            set {
                this.instrumentsSetupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public HardwareSetupType HardwareSetup {
            get {
                return this.hardwareSetupField;
            }
            set {
                this.hardwareSetupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ChipSetupType ChipSetup {
            get {
                return this.chipSetupField;
            }
            set {
                this.chipSetupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TestProcedure_cls TestProcedure {
            get {
                return this.testProcedureField;
            }
            set {
                this.testProcedureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProcessResults_cls StoreResults {
            get {
                return this.storeResultsField;
            }
            set {
                this.storeResultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SchemaInfoType SchemaInfo {
            get {
                return this.schemaInfoField;
            }
            set {
                this.schemaInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SupportEnums_cls SupportEnums {
            get {
                return this.supportEnumsField;
            }
            set {
                this.supportEnumsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Documentation_cls {
        
        private string testIDField;
        
        private int testNumberField;
        
        private string testNameField;
        
        private string testPurposeField;
        
        private string testCaseDocumentationField;
        
        private References_cls[] referencesField;
        
        private string versionField;
        
        private TestScope_cls testScopeField;
        
        private TestDut_cls[] testDUTsField;
        
        private TestGrouping_cls testGroupingField;
        
        private Parameter_cls[] testCaseParametersField;
        
        private SignalInterface_cls[] signalInterfaceField;
        
        private decimal testTimeEstimateField;
        
        private decimal testTimeATEField;
        
        private int criticalityLevelField;
        
        public Documentation_cls() {
            this.testIDField = "";
            this.testNumberField = 0;
            this.testNameField = "";
            this.testPurposeField = "";
            this.testCaseDocumentationField = "";
            this.versionField = "";
            this.testTimeEstimateField = ((decimal)(0m));
            this.testTimeATEField = ((decimal)(0m));
            this.criticalityLevelField = 0;
        }
        
        /// <remarks/>
        public string TestID {
            get {
                return this.testIDField;
            }
            set {
                this.testIDField = value;
            }
        }
        
        /// <remarks/>
        public int TestNumber {
            get {
                return this.testNumberField;
            }
            set {
                this.testNumberField = value;
            }
        }
        
        /// <remarks/>
        public string TestName {
            get {
                return this.testNameField;
            }
            set {
                this.testNameField = value;
            }
        }
        
        /// <remarks/>
        public string TestPurpose {
            get {
                return this.testPurposeField;
            }
            set {
                this.testPurposeField = value;
            }
        }
        
        /// <remarks/>
        public string TestCaseDocumentation {
            get {
                return this.testCaseDocumentationField;
            }
            set {
                this.testCaseDocumentationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("References")]
        public References_cls[] References {
            get {
                return this.referencesField;
            }
            set {
                this.referencesField = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public TestScope_cls TestScope {
            get {
                return this.testScopeField;
            }
            set {
                this.testScopeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TestDUTs")]
        public TestDut_cls[] TestDUTs {
            get {
                return this.testDUTsField;
            }
            set {
                this.testDUTsField = value;
            }
        }
        
        /// <remarks/>
        public TestGrouping_cls TestGrouping {
            get {
                return this.testGroupingField;
            }
            set {
                this.testGroupingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TestCaseParameters")]
        public Parameter_cls[] TestCaseParameters {
            get {
                return this.testCaseParametersField;
            }
            set {
                this.testCaseParametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SignalInterface")]
        public SignalInterface_cls[] SignalInterface {
            get {
                return this.signalInterfaceField;
            }
            set {
                this.signalInterfaceField = value;
            }
        }
        
        /// <remarks/>
        public decimal TestTimeEstimate {
            get {
                return this.testTimeEstimateField;
            }
            set {
                this.testTimeEstimateField = value;
            }
        }
        
        /// <remarks/>
        public decimal TestTimeATE {
            get {
                return this.testTimeATEField;
            }
            set {
                this.testTimeATEField = value;
            }
        }
        
        /// <remarks/>
        public int CriticalityLevel {
            get {
                return this.criticalityLevelField;
            }
            set {
                this.criticalityLevelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class References_cls {
        
        private string documentNumberField;
        
        private string revField;
        
        private string titleField;
        
        public References_cls() {
            this.documentNumberField = "";
            this.revField = "";
            this.titleField = "";
        }
        
        /// <remarks/>
        public string DocumentNumber {
            get {
                return this.documentNumberField;
            }
            set {
                this.documentNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Rev {
            get {
                return this.revField;
            }
            set {
                this.revField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SupportEnums_cls {
        
        private Action_enum actionField;
        
        private CONSubGroup_enum cONSubGroupField;
        
        private CURSubGroup_enum cURSubGroupField;
        
        private DIGSubGroup_enum dIGSubGroupField;
        
        private ANASubGroup_enum aNASubGroupField;
        
        private RXSubGroup_enum rXSubGroupField;
        
        private TXSubGroup_enum tXSubGroupField;
        
        private tb1SubGroup_enum tb1SubGroupField;
        
        private NVMSubGroup_enum nVMSubGroupField;
        
        private tb2SubGroup_enum tb2SubGroupField;
        
        private DBGSubGroup_enum dBGSubGroupField;
        
        /// <remarks/>
        public Action_enum Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        public CONSubGroup_enum CONSubGroup {
            get {
                return this.cONSubGroupField;
            }
            set {
                this.cONSubGroupField = value;
            }
        }
        
        /// <remarks/>
        public CURSubGroup_enum CURSubGroup {
            get {
                return this.cURSubGroupField;
            }
            set {
                this.cURSubGroupField = value;
            }
        }
        
        /// <remarks/>
        public DIGSubGroup_enum DIGSubGroup {
            get {
                return this.dIGSubGroupField;
            }
            set {
                this.dIGSubGroupField = value;
            }
        }
        
        /// <remarks/>
        public ANASubGroup_enum ANASubGroup {
            get {
                return this.aNASubGroupField;
            }
            set {
                this.aNASubGroupField = value;
            }
        }
        
        /// <remarks/>
        public RXSubGroup_enum RXSubGroup {
            get {
                return this.rXSubGroupField;
            }
            set {
                this.rXSubGroupField = value;
            }
        }
        
        /// <remarks/>
        public TXSubGroup_enum TXSubGroup {
            get {
                return this.tXSubGroupField;
            }
            set {
                this.tXSubGroupField = value;
            }
        }
        
        /// <remarks/>
        public tb1SubGroup_enum tb1SubGroup {
            get {
                return this.tb1SubGroupField;
            }
            set {
                this.tb1SubGroupField = value;
            }
        }
        
        /// <remarks/>
        public NVMSubGroup_enum NVMSubGroup {
            get {
                return this.nVMSubGroupField;
            }
            set {
                this.nVMSubGroupField = value;
            }
        }
        
        /// <remarks/>
        public tb2SubGroup_enum tb2SubGroup {
            get {
                return this.tb2SubGroupField;
            }
            set {
                this.tb2SubGroupField = value;
            }
        }
        
        /// <remarks/>
        public DBGSubGroup_enum DBGSubGroup {
            get {
                return this.dBGSubGroupField;
            }
            set {
                this.dBGSubGroupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    public enum Action_enum {
        
        /// <remarks/>
        Measure,
        
        /// <remarks/>
        Force,
        
        /// <remarks/>
        SubRoutine,
        
        /// <remarks/>
        InstrumentsSetup,
        
        /// <remarks/>
        StartLoop,
        
        /// <remarks/>
        EndLoop,
        
        /// <remarks/>
        Trim,
        
        /// <remarks/>
        Wait,
        
        /// <remarks/>
        RawText,
        
        /// <remarks/>
        MathFunction,
        
        /// <remarks/>
        RunScript,
        
        /// <remarks/>
        PowerDown,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    public enum CONSubGroup_enum {
        
        /// <remarks/>
        CON_sb1,
        
        /// <remarks/>
        CON_sb2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    public enum CURSubGroup_enum {
        
        /// <remarks/>
        X32M,
        
        /// <remarks/>
        RC32M,
        
        /// <remarks/>
        X32K,
        
        /// <remarks/>
        RC32K,
        
        /// <remarks/>
        MEMRET,
        
        /// <remarks/>
        DCDC,
        
        /// <remarks/>
        CPU,
        
        /// <remarks/>
        UART,
        
        /// <remarks/>
        SPI,
        
        /// <remarks/>
        I2C,
        
        /// <remarks/>
        GPIOTE,
        
        /// <remarks/>
        ADC,
        
        /// <remarks/>
        TIMER,
        
        /// <remarks/>
        RTC,
        
        /// <remarks/>
        TEMP,
        
        /// <remarks/>
        RNG,
        
        /// <remarks/>
        CRYPTO,
        
        /// <remarks/>
        WDT,
        
        /// <remarks/>
        QDEC,
        
        /// <remarks/>
        LPC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    public enum DIGSubGroup_enum {
        
        /// <remarks/>
        PAD_FUNC,
        
        /// <remarks/>
        DIG_LO_DRV,
        
        /// <remarks/>
        PAD_HI_DRV,
        
        /// <remarks/>
        PAD_PD,
        
        /// <remarks/>
        PAD_TINY,
        
        /// <remarks/>
        PAD_HIZ,
        
        /// <remarks/>
        IDDQ,
        
        /// <remarks/>
        MISR,
        
        /// <remarks/>
        BIST,
        
        /// <remarks/>
        FLASH_ERASE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    public enum ANASubGroup_enum {
        
        /// <remarks/>
        VBG,
        
        /// <remarks/>
        VREG,
        
        /// <remarks/>
        XOSC16M,
        
        /// <remarks/>
        RCOSC16M,
        
        /// <remarks/>
        XOSC32K,
        
        /// <remarks/>
        RCOSC32K,
        
        /// <remarks/>
        POF,
        
        /// <remarks/>
        RNG,
        
        /// <remarks/>
        ADC,
        
        /// <remarks/>
        TEMP,
        
        /// <remarks/>
        DCDC,
        
        /// <remarks/>
        PAD,
        
        /// <remarks/>
        VREF1V2,
        
        /// <remarks/>
        GPCMP,
        
        /// <remarks/>
        ATB,
        
        /// <remarks/>
        RadioPbias,
        
        /// <remarks/>
        XOSC32M,
        
        /// <remarks/>
        BOR,
        
        /// <remarks/>
        POR,
        
        /// <remarks/>
        PLL,
        
        /// <remarks/>
        WUCMP,
        
        /// <remarks/>
        RCOSC32M,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    public enum RXSubGroup_enum {
        
        /// <remarks/>
        Current,
        
        /// <remarks/>
        RXSense,
        
        /// <remarks/>
        C_IAndSelectivity,
        
        /// <remarks/>
        IMD,
        
        /// <remarks/>
        MaxInput,
        
        /// <remarks/>
        Blocking,
        
        /// <remarks/>
        RSSI,
        
        /// <remarks/>
        VCO,
        
        /// <remarks/>
        PERMap,
        
        /// <remarks/>
        Spur,
        
        /// <remarks/>
        PN,
        
        /// <remarks/>
        RxDebug,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    public enum TXSubGroup_enum {
        
        /// <remarks/>
        Current,
        
        /// <remarks/>
        OP,
        
        /// <remarks/>
        ModChar,
        
        /// <remarks/>
        CarrierDrift,
        
        /// <remarks/>
        OBW,
        
        /// <remarks/>
        ACP,
        
        /// <remarks/>
        Spur,
        
        /// <remarks/>
        VCO,
        
        /// <remarks/>
        PN,
        
        /// <remarks/>
        Tele,
        
        /// <remarks/>
        TxDebug,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    public enum tb1SubGroup_enum {
        
        /// <remarks/>
        tb1_sb1,
        
        /// <remarks/>
        tb1_sb2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    public enum NVMSubGroup_enum {
        
        /// <remarks/>
        NVM_sb1,
        
        /// <remarks/>
        NVM_sb2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    public enum tb2SubGroup_enum {
        
        /// <remarks/>
        tb2_sb1,
        
        /// <remarks/>
        tb2_sb2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    public enum DBGSubGroup_enum {
        
        /// <remarks/>
        DBG_sb1,
        
        /// <remarks/>
        DBG_sb2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SchemaInfoType {
        
        private System.DateTime dateField;
        
        private decimal versionField;
        
        private string pathField;
        
        public SchemaInfoType() {
            this.dateField = new System.DateTime(635487552000000000);
            this.versionField = ((decimal)(0.6m));
            this.pathField = "/schemas/nXML_TCD.xsd";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public decimal Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessResults_cls {
        
        private string sTDFField;
        
        private string dbField;
        
        public ProcessResults_cls() {
            this.sTDFField = "";
            this.dbField = "";
        }
        
        /// <remarks/>
        public string STDF {
            get {
                return this.sTDFField;
            }
            set {
                this.sTDFField = value;
            }
        }
        
        /// <remarks/>
        public string DB {
            get {
                return this.dbField;
            }
            set {
                this.dbField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestProcedure_cls {
        
        private int elementsNumberField;
        
        private baseAction[] actionsField;
        
        public TestProcedure_cls() {
            this.elementsNumberField = 0;
        }
        
        /// <remarks/>
        public int ElementsNumber {
            get {
                return this.elementsNumberField;
            }
            set {
                this.elementsNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("actions")]
        public baseAction[] actions {
            get {
                return this.actionsField;
            }
            set {
                this.actionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Wait_cls))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MathFunction_cls))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RunScript_cls))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RawText_cls))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PowerDown_cls))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubRoutine_cls))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ForceFunction_cls))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TrimFunction_cls))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EndLoop_cls))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StartLoop_cls))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MeasurementFunction_cls))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Instrument_cls))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class baseAction {
        
        private int sequenceField;
        
        public baseAction() {
            this.sequenceField = 0;
        }
        
        /// <remarks/>
        public int Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Wait_cls : baseAction {
        
        private decimal timeField;
        
        private string unitsField;
        
        public Wait_cls() {
            this.unitsField = "us";
        }
        
        /// <remarks/>
        public decimal Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        public string Units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MathFunction_cls : baseAction {
        
        private string inputVarsField;
        
        private string outputVarsField;
        
        private string functionToComputeField;
        
        public MathFunction_cls() {
            this.inputVarsField = "";
            this.outputVarsField = "";
            this.functionToComputeField = "";
        }
        
        /// <remarks/>
        public string InputVars {
            get {
                return this.inputVarsField;
            }
            set {
                this.inputVarsField = value;
            }
        }
        
        /// <remarks/>
        public string OutputVars {
            get {
                return this.outputVarsField;
            }
            set {
                this.outputVarsField = value;
            }
        }
        
        /// <remarks/>
        public string FunctionToCompute {
            get {
                return this.functionToComputeField;
            }
            set {
                this.functionToComputeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RunScript_cls : baseAction {
        
        private string inputVarsField;
        
        private string outputVarsField;
        
        private FileReference_cls scriptToRunField;
        
        /// <remarks/>
        public string InputVars {
            get {
                return this.inputVarsField;
            }
            set {
                this.inputVarsField = value;
            }
        }
        
        /// <remarks/>
        public string OutputVars {
            get {
                return this.outputVarsField;
            }
            set {
                this.outputVarsField = value;
            }
        }
        
        /// <remarks/>
        public FileReference_cls ScriptToRun {
            get {
                return this.scriptToRunField;
            }
            set {
                this.scriptToRunField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FileReference_cls {
        
        private string folderField;
        
        private string fileField;
        
        private string revisionField;
        
        /// <remarks/>
        public string Folder {
            get {
                return this.folderField;
            }
            set {
                this.folderField = value;
            }
        }
        
        /// <remarks/>
        public string File {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
            }
        }
        
        /// <remarks/>
        public string Revision {
            get {
                return this.revisionField;
            }
            set {
                this.revisionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RawText_cls : baseAction {
        
        private string textInputField;
        
        public RawText_cls() {
            this.textInputField = "";
        }
        
        /// <remarks/>
        public string TextInput {
            get {
                return this.textInputField;
            }
            set {
                this.textInputField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PowerDown_cls : baseAction {
        
        private string realmField;
        
        public PowerDown_cls() {
            this.realmField = "";
        }
        
        /// <remarks/>
        public string Realm {
            get {
                return this.realmField;
            }
            set {
                this.realmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubRoutine_cls : baseAction {
        
        private string nameField;
        
        private Param_cls[] paramsField;
        
        private string commentsField;
        
        public SubRoutine_cls() {
            this.nameField = "";
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Params")]
        public Param_cls[] Params {
            get {
                return this.paramsField;
            }
            set {
                this.paramsField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Param_cls {
        
        private string paramField;
        
        private string valueField;
        
        public Param_cls() {
            this.paramField = "";
            this.valueField = "";
        }
        
        /// <remarks/>
        public string Param {
            get {
                return this.paramField;
            }
            set {
                this.paramField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ForceFunction_cls : baseAction {
        
        private Force_enum kindField;
        
        private PinAndValue_cls[] pinsField;
        
        private Param_cls[] paramsField;
        
        private string commentsField;
        
        public ForceFunction_cls() {
            this.kindField = Force_enum.Voltage;
        }
        
        /// <remarks/>
        public Force_enum Kind {
            get {
                return this.kindField;
            }
            set {
                this.kindField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Pins")]
        public PinAndValue_cls[] Pins {
            get {
                return this.pinsField;
            }
            set {
                this.pinsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Params")]
        public Param_cls[] Params {
            get {
                return this.paramsField;
            }
            set {
                this.paramsField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    public enum Force_enum {
        
        /// <remarks/>
        Voltage,
        
        /// <remarks/>
        Current,
        
        /// <remarks/>
        Frequency,
        
        /// <remarks/>
        RFPacket,
        
        /// <remarks/>
        Pattern,
        
        /// <remarks/>
        Function,
        
        /// <remarks/>
        Set,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PinAndValue_cls {
        
        private string pinNameField;
        
        private string valueField;
        
        public PinAndValue_cls() {
            this.pinNameField = "";
            this.valueField = "";
        }
        
        /// <remarks/>
        public string PinName {
            get {
                return this.pinNameField;
            }
            set {
                this.pinNameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TrimFunction_cls : baseAction {
        
        private Trim_enum kindField;
        
        private string pinField;
        
        private string parameterField;
        
        private decimal thresholdField;
        
        private int maxIterationsField;
        
        private string commentsField;
        
        public TrimFunction_cls() {
            this.kindField = Trim_enum.TrimVoltage;
            this.pinField = "";
            this.parameterField = "";
            this.thresholdField = ((decimal)(0.0m));
            this.maxIterationsField = 0;
        }
        
        /// <remarks/>
        public Trim_enum Kind {
            get {
                return this.kindField;
            }
            set {
                this.kindField = value;
            }
        }
        
        /// <remarks/>
        public string Pin {
            get {
                return this.pinField;
            }
            set {
                this.pinField = value;
            }
        }
        
        /// <remarks/>
        public string Parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
        
        /// <remarks/>
        public decimal Threshold {
            get {
                return this.thresholdField;
            }
            set {
                this.thresholdField = value;
            }
        }
        
        /// <remarks/>
        public int MaxIterations {
            get {
                return this.maxIterationsField;
            }
            set {
                this.maxIterationsField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    public enum Trim_enum {
        
        /// <remarks/>
        TrimVoltage,
        
        /// <remarks/>
        TrimCurrent,
        
        /// <remarks/>
        TrimFrequency,
        
        /// <remarks/>
        TrimDeviation,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EndLoop_cls : baseAction {
        
        private string labelField;
        
        public EndLoop_cls() {
            this.labelField = "";
        }
        
        /// <remarks/>
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StartLoop_cls : baseAction {
        
        private string variableField;
        
        private string valuesField;
        
        private string endLoopLabelField;
        
        public StartLoop_cls() {
            this.variableField = "";
            this.valuesField = "";
            this.endLoopLabelField = "";
        }
        
        /// <remarks/>
        public string Variable {
            get {
                return this.variableField;
            }
            set {
                this.variableField = value;
            }
        }
        
        /// <remarks/>
        public string Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
            }
        }
        
        /// <remarks/>
        public string EndLoopLabel {
            get {
                return this.endLoopLabelField;
            }
            set {
                this.endLoopLabelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MeasurementFunction_cls : baseAction {
        
        private Measurement_enum kindField;
        
        private string pinField;
        
        private string parameterField;
        
        private string commentsField;
        
        public MeasurementFunction_cls() {
            this.kindField = Measurement_enum.Voltage;
            this.pinField = "";
            this.parameterField = "";
        }
        
        /// <remarks/>
        public Measurement_enum Kind {
            get {
                return this.kindField;
            }
            set {
                this.kindField = value;
            }
        }
        
        /// <remarks/>
        public string Pin {
            get {
                return this.pinField;
            }
            set {
                this.pinField = value;
            }
        }
        
        /// <remarks/>
        public string Parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
        
        /// <remarks/>
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    public enum Measurement_enum {
        
        /// <remarks/>
        Voltage,
        
        /// <remarks/>
        Current,
        
        /// <remarks/>
        Frequency,
        
        /// <remarks/>
        Digital,
        
        /// <remarks/>
        FVMI,
        
        /// <remarks/>
        FIMV,
        
        /// <remarks/>
        RFPower,
        
        /// <remarks/>
        RFSensitivity,
        
        /// <remarks/>
        RFAcquisition,
        
        /// <remarks/>
        Pattern,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Instrument_cls : baseAction {
        
        private string instrumentNameField;
        
        private InstrumentKind_enum instrumentKindField;
        
        private Param_cls[] paramsField;
        
        /// <remarks/>
        public string InstrumentName {
            get {
                return this.instrumentNameField;
            }
            set {
                this.instrumentNameField = value;
            }
        }
        
        /// <remarks/>
        public InstrumentKind_enum InstrumentKind {
            get {
                return this.instrumentKindField;
            }
            set {
                this.instrumentKindField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Params")]
        public Param_cls[] Params {
            get {
                return this.paramsField;
            }
            set {
                this.paramsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    public enum InstrumentKind_enum {
        
        /// <remarks/>
        Voltmeter,
        
        /// <remarks/>
        Ampmeter,
        
        /// <remarks/>
        Digitizer,
        
        /// <remarks/>
        PowerSupply,
        
        /// <remarks/>
        FunctionGen,
        
        /// <remarks/>
        Switch,
        
        /// <remarks/>
        PPMU,
        
        /// <remarks/>
        RFGen,
        
        /// <remarks/>
        RFDig,
        
        /// <remarks/>
        RFSwitch,
        
        /// <remarks/>
        RFTranceiver,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InitChip_cls {
        
        private string preConditionField;
        
        private FileReference_cls loadFWField;
        
        private FileReference_cls executePatternField;
        
        public InitChip_cls() {
            this.preConditionField = "";
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string PreCondition {
            get {
                return this.preConditionField;
            }
            set {
                this.preConditionField = value;
            }
        }
        
        /// <remarks/>
        public FileReference_cls LoadFW {
            get {
                return this.loadFWField;
            }
            set {
                this.loadFWField = value;
            }
        }
        
        /// <remarks/>
        public FileReference_cls ExecutePattern {
            get {
                return this.executePatternField;
            }
            set {
                this.executePatternField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InitPin_cls {
        
        private string pinNameField;
        
        private PinState_enum stateField;
        
        private string commentsField;
        
        public InitPin_cls() {
            this.pinNameField = "";
            this.stateField = PinState_enum.Disconnected;
            this.commentsField = "";
        }
        
        /// <remarks/>
        public string PinName {
            get {
                return this.pinNameField;
            }
            set {
                this.pinNameField = value;
            }
        }
        
        /// <remarks/>
        public PinState_enum State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    public enum PinState_enum {
        
        /// <remarks/>
        Disconnected,
        
        /// <remarks/>
        Input,
        
        /// <remarks/>
        Output,
        
        /// <remarks/>
        Analog,
        
        /// <remarks/>
        RF,
        
        /// <remarks/>
        BiDirectional,
        
        /// <remarks/>
        OutputHigh,
        
        /// <remarks/>
        OutputLow,
        
        /// <remarks/>
        Power,
        
        /// <remarks/>
        Ground,
        
        /// <remarks/>
        Clock,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PowerUp_cls {
        
        private PinAndValue_cls[] applyPowerField;
        
        private Wait_cls waitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ApplyPower")]
        public PinAndValue_cls[] ApplyPower {
            get {
                return this.applyPowerField;
            }
            set {
                this.applyPowerField = value;
            }
        }
        
        /// <remarks/>
        public Wait_cls Wait {
            get {
                return this.waitField;
            }
            set {
                this.waitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChipSetupType {
        
        private PowerUp_cls powerUpField;
        
        private InitPin_cls[] initPinsField;
        
        private InitChip_cls initChipField;
        
        /// <remarks/>
        public PowerUp_cls PowerUp {
            get {
                return this.powerUpField;
            }
            set {
                this.powerUpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InitPins")]
        public InitPin_cls[] InitPins {
            get {
                return this.initPinsField;
            }
            set {
                this.initPinsField = value;
            }
        }
        
        /// <remarks/>
        public InitChip_cls InitChip {
            get {
                return this.initChipField;
            }
            set {
                this.initChipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HardwareSetupType {
        
        private FileReference_cls aTEHWDescriptorField;
        
        private FileReference_cls lABHWDescriptorField;
        
        /// <remarks/>
        public FileReference_cls ATEHWDescriptor {
            get {
                return this.aTEHWDescriptorField;
            }
            set {
                this.aTEHWDescriptorField = value;
            }
        }
        
        /// <remarks/>
        public FileReference_cls LABHWDescriptor {
            get {
                return this.lABHWDescriptorField;
            }
            set {
                this.lABHWDescriptorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExternalVars_cls {
        
        private string nameField;
        
        private VarType_enum typeField;
        
        private string defaultField;
        
        private string commentField;
        
        public ExternalVars_cls() {
            this.nameField = "";
            this.typeField = VarType_enum.String;
            this.defaultField = "";
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public VarType_enum Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    public enum VarType_enum {
        
        /// <remarks/>
        Int,
        
        /// <remarks/>
        Long,
        
        /// <remarks/>
        Array,
        
        /// <remarks/>
        String,
        
        /// <remarks/>
        Variant,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SignalInterface_cls {
        
        private string padField;
        
        private SignalType typeField;
        
        private PinState_enum stateField;
        
        private string functionField;
        
        private string commentField;
        
        public SignalInterface_cls() {
            this.padField = "";
            this.functionField = "";
            this.commentField = "";
        }
        
        /// <remarks/>
        public string Pad {
            get {
                return this.padField;
            }
            set {
                this.padField = value;
            }
        }
        
        /// <remarks/>
        public SignalType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public PinState_enum State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string Function {
            get {
                return this.functionField;
            }
            set {
                this.functionField = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    public enum SignalType {
        
        /// <remarks/>
        Analog,
        
        /// <remarks/>
        Digital,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Parameter_cls {
        
        private string nameField;
        
        private string modeField;
        
        private string descriptionField;
        
        private int softBinField;
        
        private decimal lAB_NTC_MinField;
        
        private decimal lAB_NTC_TypField;
        
        private decimal lAB_NTC_MaxField;
        
        private decimal lAB_ETC_MinField;
        
        private decimal lAB_ETC_MaxField;
        
        private decimal aTE_NTC_MinField;
        
        private decimal aTE_NTC_MaxField;
        
        private decimal aTE_ETC_MinField;
        
        private decimal aTE_ETC_MaxField;
        
        private string unitField;
        
        public Parameter_cls() {
            this.nameField = "";
            this.modeField = "";
            this.descriptionField = "";
            this.softBinField = 0;
            this.lAB_NTC_MinField = ((decimal)(0m));
            this.lAB_NTC_TypField = ((decimal)(0m));
            this.lAB_NTC_MaxField = ((decimal)(0m));
            this.lAB_ETC_MinField = ((decimal)(0m));
            this.lAB_ETC_MaxField = ((decimal)(0m));
            this.aTE_NTC_MinField = ((decimal)(0m));
            this.aTE_NTC_MaxField = ((decimal)(0m));
            this.aTE_ETC_MinField = ((decimal)(0m));
            this.aTE_ETC_MaxField = ((decimal)(0m));
            this.unitField = "";
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int SoftBin {
            get {
                return this.softBinField;
            }
            set {
                this.softBinField = value;
            }
        }
        
        /// <remarks/>
        public decimal LAB_NTC_Min {
            get {
                return this.lAB_NTC_MinField;
            }
            set {
                this.lAB_NTC_MinField = value;
            }
        }
        
        /// <remarks/>
        public decimal LAB_NTC_Typ {
            get {
                return this.lAB_NTC_TypField;
            }
            set {
                this.lAB_NTC_TypField = value;
            }
        }
        
        /// <remarks/>
        public decimal LAB_NTC_Max {
            get {
                return this.lAB_NTC_MaxField;
            }
            set {
                this.lAB_NTC_MaxField = value;
            }
        }
        
        /// <remarks/>
        public decimal LAB_ETC_Min {
            get {
                return this.lAB_ETC_MinField;
            }
            set {
                this.lAB_ETC_MinField = value;
            }
        }
        
        /// <remarks/>
        public decimal LAB_ETC_Max {
            get {
                return this.lAB_ETC_MaxField;
            }
            set {
                this.lAB_ETC_MaxField = value;
            }
        }
        
        /// <remarks/>
        public decimal ATE_NTC_Min {
            get {
                return this.aTE_NTC_MinField;
            }
            set {
                this.aTE_NTC_MinField = value;
            }
        }
        
        /// <remarks/>
        public decimal ATE_NTC_Max {
            get {
                return this.aTE_NTC_MaxField;
            }
            set {
                this.aTE_NTC_MaxField = value;
            }
        }
        
        /// <remarks/>
        public decimal ATE_ETC_Min {
            get {
                return this.aTE_ETC_MinField;
            }
            set {
                this.aTE_ETC_MinField = value;
            }
        }
        
        /// <remarks/>
        public decimal ATE_ETC_Max {
            get {
                return this.aTE_ETC_MaxField;
            }
            set {
                this.aTE_ETC_MaxField = value;
            }
        }
        
        /// <remarks/>
        public string Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestSuiteType {
        
        private string relativePathField;
        
        private DeviceType deviceField;
        
        private TestCaseType[] testCaseField;
        
        public TestSuiteType() {
            this.relativePathField = "../xmls";
        }
        
        /// <remarks/>
        public string RelativePath {
            get {
                return this.relativePathField;
            }
            set {
                this.relativePathField = value;
            }
        }
        
        /// <remarks/>
        public DeviceType Device {
            get {
                return this.deviceField;
            }
            set {
                this.deviceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TestCase")]
        public TestCaseType[] TestCase {
            get {
                return this.testCaseField;
            }
            set {
                this.testCaseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeviceType {
        
        private string familyField;
        
        private PackageType packageField;
        
        private string packageSizeField;
        
        private PowerSupplyType powerSupplyRatingField;
        
        private TemperatureType temperatureRatingField;
        
        private PinType[] pinsField;
        
        private PadType[] padsField;
        
        public DeviceType() {
            this.familyField = "";
            this.packageSizeField = "";
        }
        
        /// <remarks/>
        public string Family {
            get {
                return this.familyField;
            }
            set {
                this.familyField = value;
            }
        }
        
        /// <remarks/>
        public PackageType Package {
            get {
                return this.packageField;
            }
            set {
                this.packageField = value;
            }
        }
        
        /// <remarks/>
        public string PackageSize {
            get {
                return this.packageSizeField;
            }
            set {
                this.packageSizeField = value;
            }
        }
        
        /// <remarks/>
        public PowerSupplyType PowerSupplyRating {
            get {
                return this.powerSupplyRatingField;
            }
            set {
                this.powerSupplyRatingField = value;
            }
        }
        
        /// <remarks/>
        public TemperatureType TemperatureRating {
            get {
                return this.temperatureRatingField;
            }
            set {
                this.temperatureRatingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Pins")]
        public PinType[] Pins {
            get {
                return this.pinsField;
            }
            set {
                this.pinsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Pads")]
        public PadType[] Pads {
            get {
                return this.padsField;
            }
            set {
                this.padsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    public enum PackageType {
        
        /// <remarks/>
        QFN24,
        
        /// <remarks/>
        QFN32,
        
        /// <remarks/>
        QFN40,
        
        /// <remarks/>
        QFN48,
        
        /// <remarks/>
        CSP68,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PowerSupplyType {
        
        private decimal vddMinField;
        
        private decimal vddNomField;
        
        private decimal vddMaxField;
        
        public PowerSupplyType() {
            this.vddMinField = ((decimal)(1.9m));
            this.vddNomField = ((decimal)(3m));
            this.vddMaxField = ((decimal)(3.6m));
        }
        
        /// <remarks/>
        public decimal VddMin {
            get {
                return this.vddMinField;
            }
            set {
                this.vddMinField = value;
            }
        }
        
        /// <remarks/>
        public decimal VddNom {
            get {
                return this.vddNomField;
            }
            set {
                this.vddNomField = value;
            }
        }
        
        /// <remarks/>
        public decimal VddMax {
            get {
                return this.vddMaxField;
            }
            set {
                this.vddMaxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TemperatureType {
        
        private decimal tempMinField;
        
        private decimal tempNomField;
        
        private decimal tempMaxField;
        
        public TemperatureType() {
            this.tempMinField = ((decimal)(-25m));
            this.tempNomField = ((decimal)(25m));
            this.tempMaxField = ((decimal)(75m));
        }
        
        /// <remarks/>
        public decimal TempMin {
            get {
                return this.tempMinField;
            }
            set {
                this.tempMinField = value;
            }
        }
        
        /// <remarks/>
        public decimal TempNom {
            get {
                return this.tempNomField;
            }
            set {
                this.tempNomField = value;
            }
        }
        
        /// <remarks/>
        public decimal TempMax {
            get {
                return this.tempMaxField;
            }
            set {
                this.tempMaxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PinType {
        
        private int pinNumberField;
        
        private string pinNameField;
        
        private string padNameField;
        
        private string testFunctionField;
        
        public PinType() {
            this.pinNameField = "";
            this.padNameField = "";
            this.testFunctionField = "";
        }
        
        /// <remarks/>
        public int PinNumber {
            get {
                return this.pinNumberField;
            }
            set {
                this.pinNumberField = value;
            }
        }
        
        /// <remarks/>
        public string PinName {
            get {
                return this.pinNameField;
            }
            set {
                this.pinNameField = value;
            }
        }
        
        /// <remarks/>
        public string PadName {
            get {
                return this.padNameField;
            }
            set {
                this.padNameField = value;
            }
        }
        
        /// <remarks/>
        public string TestFunction {
            get {
                return this.testFunctionField;
            }
            set {
                this.testFunctionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PadType {
        
        private string padNameField;
        
        private string testFunctionField;
        
        public PadType() {
            this.padNameField = "";
            this.testFunctionField = "";
        }
        
        /// <remarks/>
        public string PadName {
            get {
                return this.padNameField;
            }
            set {
                this.padNameField = value;
            }
        }
        
        /// <remarks/>
        public string TestFunction {
            get {
                return this.testFunctionField;
            }
            set {
                this.testFunctionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestCaseType {
        
        private object fileXmlField;
        
        /// <remarks/>
        public object FileXml {
            get {
                return this.fileXmlField;
            }
            set {
                this.fileXmlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestSubGroup_cls {
        
        private object itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ANASubGroup_enum", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("CONSubGroup_enum", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("CURSubGroup_enum", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("DBGSubGroup_enum", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("DIGSubGroup_enum", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("NVMSubGroup_enum", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("RXSubGroup_enum", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("TXSubGroup_enum", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("tb1SubGroup_enum", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("tb2SubGroup_enum", typeof(object))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        ANASubGroup_enum,
        
        /// <remarks/>
        CONSubGroup_enum,
        
        /// <remarks/>
        CURSubGroup_enum,
        
        /// <remarks/>
        DBGSubGroup_enum,
        
        /// <remarks/>
        DIGSubGroup_enum,
        
        /// <remarks/>
        NVMSubGroup_enum,
        
        /// <remarks/>
        RXSubGroup_enum,
        
        /// <remarks/>
        TXSubGroup_enum,
        
        /// <remarks/>
        tb1SubGroup_enum,
        
        /// <remarks/>
        tb2SubGroup_enum,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestGrouping_cls {
        
        private TestGroup_enum testGroupField;
        
        private TestSubGroup_cls testSubGroupField;
        
        /// <remarks/>
        public TestGroup_enum TestGroup {
            get {
                return this.testGroupField;
            }
            set {
                this.testGroupField = value;
            }
        }
        
        /// <remarks/>
        public TestSubGroup_cls TestSubGroup {
            get {
                return this.testSubGroupField;
            }
            set {
                this.testSubGroupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    public enum TestGroup_enum {
        
        /// <remarks/>
        CON,
        
        /// <remarks/>
        CUR,
        
        /// <remarks/>
        DIG,
        
        /// <remarks/>
        ANA,
        
        /// <remarks/>
        RX,
        
        /// <remarks/>
        TX,
        
        /// <remarks/>
        tb1,
        
        /// <remarks/>
        NVM,
        
        /// <remarks/>
        tb2,
        
        /// <remarks/>
        DBG,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestDut_cls {
        
        private string dUTField;
        
        private int hWIDField;
        
        private string nickNameField;
        
        private string xmlFileField;
        
        private string revisionField;
        
        public TestDut_cls() {
            this.dUTField = "";
            this.hWIDField = 0;
            this.nickNameField = "";
            this.xmlFileField = "";
            this.revisionField = "";
        }
        
        /// <remarks/>
        public string DUT {
            get {
                return this.dUTField;
            }
            set {
                this.dUTField = value;
            }
        }
        
        /// <remarks/>
        public int HWID {
            get {
                return this.hWIDField;
            }
            set {
                this.hWIDField = value;
            }
        }
        
        /// <remarks/>
        public string NickName {
            get {
                return this.nickNameField;
            }
            set {
                this.nickNameField = value;
            }
        }
        
        /// <remarks/>
        public string XmlFile {
            get {
                return this.xmlFileField;
            }
            set {
                this.xmlFileField = value;
            }
        }
        
        /// <remarks/>
        public string Revision {
            get {
                return this.revisionField;
            }
            set {
                this.revisionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestScope_cls {
        
        private bool labEngrField;
        
        private bool labPatrField;
        
        private bool ateFtProdField;
        
        private bool ateFtCharField;
        
        private bool ateCpField;
        
        public TestScope_cls() {
            this.labEngrField = false;
            this.labPatrField = false;
            this.ateFtProdField = false;
            this.ateFtCharField = false;
            this.ateCpField = false;
        }
        
        /// <remarks/>
        public bool LabEngr {
            get {
                return this.labEngrField;
            }
            set {
                this.labEngrField = value;
            }
        }
        
        /// <remarks/>
        public bool LabPatr {
            get {
                return this.labPatrField;
            }
            set {
                this.labPatrField = value;
            }
        }
        
        /// <remarks/>
        public bool AteFtProd {
            get {
                return this.ateFtProdField;
            }
            set {
                this.ateFtProdField = value;
            }
        }
        
        /// <remarks/>
        public bool AteFtChar {
            get {
                return this.ateFtCharField;
            }
            set {
                this.ateFtCharField = value;
            }
        }
        
        /// <remarks/>
        public bool AteCp {
            get {
                return this.ateCpField;
            }
            set {
                this.ateCpField = value;
            }
        }
    }
}
